CREATE FUNCTION fn_latinica
(@tekst NVARCHAR(MAX))
RETURNS NVARCHAR(MAX)
AS
BEGIN
    DECLARE @ntekst NVARCHAR(MAX)
	SET @ntekst = @tekst
	SET @ntekst = REPLACE(@ntekst, N'Љ', N'Lj')
	SET @ntekst = REPLACE(@ntekst, N'љ', N'lj')
	SET @ntekst = REPLACE(@ntekst, N'Њ', N'Nj')
	SET @ntekst = REPLACE(@ntekst, N'њ', N'nj')
	SET @ntekst = REPLACE(@ntekst, N'Џ', N'Dž')
	SET @ntekst = REPLACE(@ntekst, N'џ', N'dž')
	
	SET @ntekst = REPLACE(@ntekst, N'А', N'A')
	SET @ntekst = REPLACE(@ntekst, N'Б', N'B')
	SET @ntekst = REPLACE(@ntekst, N'В', N'V')
	SET @ntekst = REPLACE(@ntekst, N'Г', N'G')
	SET @ntekst = REPLACE(@ntekst, N'Д', N'D')
	SET @ntekst = REPLACE(@ntekst, N'Ђ', N'Đ')
	SET @ntekst = REPLACE(@ntekst, N'Е', N'E')
	SET @ntekst = REPLACE(@ntekst, N'Ж', N'Ž')
	SET @ntekst = REPLACE(@ntekst, N'З', N'Z')
    SET @ntekst = REPLACE(@ntekst, N'И', N'I')
    SET @ntekst = REPLACE(@ntekst, N'Ј', N'J')
    SET @ntekst = REPLACE(@ntekst, N'К', N'K')
    SET @ntekst = REPLACE(@ntekst, N'Л', N'L')
    SET @ntekst = REPLACE(@ntekst, N'М', N'M')
    SET @ntekst = REPLACE(@ntekst, N'Н', N'N')
    SET @ntekst = REPLACE(@ntekst, N'О', N'O')
    SET @ntekst = REPLACE(@ntekst, N'П', N'P')
    SET @ntekst = REPLACE(@ntekst, N'Р', N'R')
    SET @ntekst = REPLACE(@ntekst, N'С', N'S')
    SET @ntekst = REPLACE(@ntekst, N'Т', N'T')
    SET @ntekst = REPLACE(@ntekst, N'Ћ', N'C')
    SET @ntekst = REPLACE(@ntekst, N'У', N'U')
    SET @ntekst = REPLACE(@ntekst, N'Ф', N'F')
    SET @ntekst = REPLACE(@ntekst, N'Х', N'H')
    SET @ntekst = REPLACE(@ntekst, N'Ц', N'C')
    SET @ntekst = REPLACE(@ntekst, N'Ч', N'C')
    SET @ntekst = REPLACE(@ntekst, N'Ш', N'Š')
    RETURN @ntekst
END
